baseURL = 'https://d19qhx4ioawdt7.cloudfront.net'
languageCode = 'en-us'
title = 'Joseph LaFreniere'

enableGitInfo = true

[params]
BookComments = false
BookCommitPath = "commit"
BookDateFormat = "2006-01-02"
BookRepo = "https://git.sr.ht/~lafrenierejm/lafreniere.xyz"
BookTheme = 'auto'

[markup.goldmark.renderer]
unsafe = true
